# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs: 
  - job:
    displayName: "Swiftlint & Unit Tests"
    steps:
      - script: bundle install 
        displayName: 'bundle install'
       
      - script: bundle exec pod install
        displayName: 'Installing pods'
  
      - script: bundle exec fastlane lint
        displayName: 'Running SwiftLint'

      - script: bundle exec fastlane build_for_tests
        displayName: 'Building for tests'

      - script: bundle exec fastlane run_tests
        continueOnError: true
        displayName: 'Running tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          failTaskOnFailedTests: true
          testResultsFiles: './fastlane/test_output/report.junit'
