# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

stages:
  - stage: swiftlint
    jobs:
      - job: swiftlint
        steps:
          - script: bundle exec fastlane line
            displayName: 'Running SwiftLint'

  - stage: unit_tests
    dependsOn: swiftlint
    jobs:
      - job: prepare_environment
        steps:
          - script: |
              CALL gem install bundler
              bundle install --retry=3 --jobs=4
            displayName: 'bundle install'

          - script: bundle exec pod install
            displayName: 'Installing pods'

      - job: build_app
        steps:
          - script: bundle exec fastlane build_for_tests
            displayName: 'Building for tests'

      - job: run_tests
        steps:
          - script: bundle exec fastlane run_tests
            continueOnError: true
            displayName: 'Running tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              failTaskOnFailedTests: true
              testResultsFiles: './fastlane/test_output/report.junit'
