default_platform(:ios)

DERIVED_DATA_PATH = "DerivedData"
platform :ios do
  desc "Description of what the lane does"

  lane :lint do
    swiftlint(
      executable: "./Pods/SwiftLint/swiftlint",
      strict: true
    )
  end

  lane :build_for_tests do
    scan(
      derived_data_path: DERIVED_DATA_PATH,
      build_for_testing: true
    )
  end

  lane :run_test do
    scan(
      derived_data_path: DERIVED_DATA_PATH,
      test_without_building: true
    )
  end

  lane :test do
    build_for_tests
    run_test
  end
end
